heat_template_version: 2013-05-23


description: Cinder Install

parameters:
    server_id:
      label: server ID  
      type: string

resources:
   cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: 20
      volume_type: standard

   volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: cinder_volume }
      instance_uuid: { get_param: server_id }
      mountpoint: /dev/vdb